project:
  type: book
  output-dir: docs

book:
  title: "book"
  author: "Norah Jones"
  date: "25/09/2024"
  chapters:
    - index.qmd
    - intro.qmd
    part: "Types of Penguin"
      chapters:
      - adelie.qmd
      - chinstrap.qmd
      - gentoo.qmd
    part: analysis.qmd
      - adelie_analysis.qmd
      - chinstrap_analysis.qmd
      - gentoo_analysis.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
